### PR TITLE
[WIP] S3 fixes and improvements

### PR DESCRIPTION
**Pull request by rcoup**
> This is WIP, there's a bunch of requirements upgrades which I ended up doing to get the dev environment working & tests passing, but I can rebase that away.

A series of S3 improvements. Happy to break them up if you want, but more after feedback at this point :-) 

### s3_external: force the upload Content-Type

git-lfs as of v2.5.0 [detects the file Content-Type and provides it during PUT requests](https://github.com/git-lfs/git-lfs/pull/3137) to the storage when using the basic transfer. If we don't include the same `Content-Type` value in the S3 signature generation, then S3 rejects the upload.

Unfortunately git-lfs doesn't pass the `Content-Type` value to the Batch request, so we can't include it in the S3 signature generation. And while setting [`lfs.contenttype=false` in the client config](https://github.com/git-lfs/git-lfs/pull/3163) forces sending `application/octet-stream`, S3 isn't happy with that either (IIUC it defaults to `binary/octet-stream` or expects `Content-Type` to be omitted).

But if the Batch response upload action includes a `Content-Type` header then git-lfs will always use that for the PUT request. So change Giftless to return `application/octet-stream`, and also use it for signature generation.

### s3_external: use sha256 checksums when uploading

Use the new S3 [content integrity support](https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html) to pass the object sha256 to S3 when uploading objects, so S3 can confirm integrity.

This requires a newer boto3 version.

### tests: s3: force us-east-1 region to match urls
If you run the tests with a different default region set in your local S3 config, you get failures. Fix it by forcing to `us-east-1`.

If you're reasonably happy I can either t

### CODE REVIEW

**Comment by mtb-xt** [comment]
@rcoup did it work for you for s3_external? I've tried with 'stock' giftless and with your patches applied, I'm still getting rejected by S3. Would you be interested in looking at it?

**Comment by rcoup** [comment]
@mtb-xt yes, is working well for me. What errors are you seeing? Using something like this should show all the requests & most of the responses that are happening, for both git itself and git-lfs' interaction with the git-lfs server & any storage endpoints.

```
GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 GIT_TRACE=1 git push
```

FWIW, I'm predominantly using EC2 instance roles with IAM roles/policies for bucket access; and git-lfs v2.13.3

**Comment by mtb-xt** [comment]
@rcoup hey, thanks for helping out! I'm getting 400 Bad Requests, which lead me to believe some of the headers are wrong -_- 
I'm using git-lfs/3.1.2 (GitHub; linux amd64; go 1.17.7)

Here are some sanitized logs -> https://gist.github.com/mtb-xt/7c8641535aa615e6f4eeea24fc4c2285

**Comment by mtb-xt** [comment]
Aha, this weird issue was that my bucket had KMS encryption key managed by AWS, and that requires using SigV4 signatures in presigned urls. 
This has nothing to do with your PR, I'll make a PR of my own to make this configurable, thanks for your help! :)

**Comment by rcoup** [comment]
Argh, their docs imply that SigV4 is now the default, but [apparently not](https://github.com/boto/botocore/issues/2109)

**Comment by mtb-xt** [comment]
@rufuspollock @shevron are you guys going to accept this PR? There are some more fixes needed for S3, but I'd like to start off from changes in this branch

**Comment by rufuspollock** [comment]
@rcoup first a big thank-you for the contribution 👍 . Really welcome. This looked good and as per @mtb-xt i have merged this. I did want to check that:

a) the PR was in good state to merge (from review and discussion seemed so but was not sure from your last comments).
b) you are happy with the MIT license

**Comment by rcoup** [comment]
@rufuspollock 
a) I've fixed the dependency issue in #103. 
b) MIT is good 👍

**Comment by rcoup** [comment]
@mtb-xt CC me in your PR please?

**Pull request merged**
