### PR TITLE
Work correctly with pyjwt 2.x

### PR DESCRIPTION
**Pull request by athornton**
The actual type of `jwt.encode()` changed from `bytes` to `str` in 2.x, but somehow the typing hints aren't keeping up, and the whole JWT typing thing is a can of worms (cf https://github.com/jpadilla/pyjwt/issues/602).

So I'm being overly defensive about what we actually got back from there, but returning a string up the call stack and modifying the function signature (and its caller).

This is the minimal necessary work to address https://github.com/datopian/giftless/issues/122

Maybe if I get some time in the New Year I can work on modernizing giftless and making its test suite more maintainable.

### CODE REVIEW

**Comment by athornton** [comment]
Test cases are passing now.  Ready for review, I think.

**Comment by rufuspollock** [comment]
@athornton great, thank-you. 👏 🙏

It looks good. Merging it in.

**Comment by gil-mahalla** [comment]
@rufuspollock 
Where can I find the 0.5.1 container? It seems to be missing from [docker hub](https://hub.docker.com/r/datopian/giftless/tags), thank you!

**Comment by rufuspollock** [comment]
@gil-mahalla we'd need to publish it - i think this is related to #119

**Comment by athornton** [comment]
@gil-mahalla if you've got the source checked out, and you've got Docker installed, `docker build -t <your-org>/giftless:0.5.1 .` should work, and then push it to your own repo.  That's basically what I'm doing for now.

`make docker` might work for you, but it wants to use an existing image as build cache, which I think is going to get you outdated versions of the libraries.  I had better luck just building the image from the Dockerfile in the repo.  (You could also change the Makefile's `DOCKER_REPO` and `DOCKER_CACHE_FROM`; those are overriding variables so you can't force them from the command line, which is arguably a bug.)

**Comment by rufuspollock** [comment]
@athornton if we could give you access to that repo on our docker hub would you up for pushing updates directly there - i imagine it would help your workflow (and that of others)?

**Comment by athornton** [comment]
Sure.  In the slightly longer term, we need the GitHub Action workflow to push on definition of a new release tag, I think, but in the interim, doing manual pushes of new artifacts would be OK with me.  I'll be back at work January 2, 2024, and we can figure it out from there.

**Pull request merged**
