### PR TITLE
Upgrade requirements

### PR DESCRIPTION
**Pull request by amercader**
Via `pip-compile requirements.in > requirements.txt` 

Ahead of some new changes that will need a new requirement.

### CODE REVIEW

**Comment by shevron** [comment]
Looks good, better to use `make requirements` as IIRC it preserves the original command line arguments (`--output-file and --no-emit-index-url`). While none of these are critical, they could be useful in some environments.

**Comment by shevron** [comment]
> Looks good, better to use `make requirements` as IIRC it preserves the original command line arguments (`--output-file and --no-emit-index-url`). While none of these are critical, they could be useful in some environments.

Actually I just realized you didn't change `requirements.in` - so forget this comment :)

**Comment by amercader** [comment]
Yes, I tried to run `make requirements` but it said `make: Nothing to be done for 'requirements'.` because the `.in` file was not touched

**Comment by shevron** [comment]
> Yes, I tried to run `make requirements` but it said `make: Nothing to be done for 'requirements'.` because the `.in` file was not touched

Yep, maybe one day I will add a ` make update-requirements` or something like that that basically upgrades requirements to latest regardless of whether there was a change or not. Should be easy enough to add.

**Pull request merged**
