### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by paluyana**
add custom module

### CODE REVIEW

**Comment by rufuspollock** [comment]
@paluyana thanks for this - could you say a bit more about what this change does 😄?

**Comment by vit-zikmund** [comment]
Hi @rufuspollock, my colleague apparently opened this PR by accident. It should have been targeted to our local fork for further polishing before taking it here (that's likely why the name is confusing and there's no description).

Since you ask though :wink:, this little piece of code aims to add a new auth provider targeting an ordinary GitHub account with a personal token and matching LFS authorization with the GitHub one.
We use GitHub for the ordinary source code, but want to spare some non-trivial cash using our homegrown storage for LFS. In order to minimize the LFS access management, we want to mirror the existing GitHub auth[n/z] and that's what  this module is for.

Would you be interested in such a contribution at all? The current code is still a bit too raw, please feel free to close the PR for now. If you're interested, we'd open a new one, once we feel like it's good enough on our side.

My original intention was be to reuse any stored github creds to seamlessly provide access to our own LFS server, but it [seems that might not work](https://github.com/git-lfs/git-lfs/issues/4060) as `git` asks for extra creds for the LFS URL (which is obviously different from github's and it normally uses the hostname for creds matching), but that's something easy to live with using a credential helper.

**Comment by athornton** [comment]
In the Rubin initial explorations of giftless, we also toyed with doing Github proxy auth.  @vit-zikmund if you want to see if there are any ideas in there you can use, it's over at https://github.com/lsst-sqre/giftless-github-proxy-auth ; ultimately we went a different direction (since we are going to be running in the context of a Phalanx deployment, we can control the front end auth, and we know we're running inside GKE, so we can use Workload Identity to let the Giftless server talk to our object storage, make Giftless itself run anonymously, and control access to the Giftless endpoints with the Phalanx auth).  But if you want to gate LFS on "would GitHub let this set of credentials push to that repo" ...

**Comment by vit-zikmund** [comment]
Thank you @athornton! That's a valuable resource at least a couple weeks ahead of us :+1:
We also have a kubernetes environment, but it's one we built from scratch on our own hardware, so it has much less of those GKE's bells and whistles. Having no urgent need for centralized auth so far, GitHub is our way to go ATM. Your  [Phalanx](https://phalanx.lsst.io/about/introduction.html) looks really nice! Still, I suppose it doesn't replace the need for the usual GitHub login, does it? I don't want to hijack this PR thread too much, but since you were so far this helpful... ;)

**Comment by rufuspollock** [comment]
> Since you ask though 😉, this little piece of code aims to add a new auth provider targeting an ordinary GitHub account with a personal token and matching LFS authorization with the GitHub one.

This is **super cool** and something we've actually wanted.

> Would you be interested in such a contribution at all? The current code is still a bit too raw, please feel free to close the PR for now. If you're interested, we'd open a new one, once we feel like it's good enough on our side.

We would be **very** interested in this kind of contribution 😄

> My original intention was be to reuse any stored github creds to seamlessly provide access to our own LFS server, but it https://github.com/git-lfs/git-lfs/issues/4060 as git asks for extra creds for the LFS URL (which is obviously different from github's and it normally uses the hostname for creds matching), but that's something easy to live with using a credential helper.

Good points and something we can write up more - i suggest we could start discussing this in an issue (or in a new PR - though starting with an issue seems like a nice approach).

All in all we'd really welcome this!

**Comment by athornton** [comment]
It does not avoid the need for the standard GitHub login (although you can tell Phalanx to use GitHub as its back-end auth provider, and then it effectively works like SSO, because you're authed to GitHub in your browser by the time you auth via Gafaelfawr to Phalanx...but that still doesn't give you transparent auth from Jupyter Notebooks, because your token inside Phalanx is not the token you've got with GitHub).

**Comment by vit-zikmund** [comment]
Thanks for the details and the offer @athornton! I'm looking for some good inspiration for a nicely controlled deployment environment, sadly, it's not quite on the top of my current duties :disappointed: I'd love to come for more study, but I don't see it any sooner than in a few months... Keeping my fingers crossed :crossed_fingers: 

@rufuspollock I've opened the issue https://github.com/datopian/giftless/issues/128, so let's move over there for further elaboration ;) PRs can come later and we can close this one.

**Pull request closed without merging**
